### ISSUE TITLE
Question: Usage

### ISSUE THREAD

**Issue by deheingit** [homecineplexx/ioBroker.homepilot20#10]
Hi and thanks a lot for writing the adapter. I'm completly new to iobroker and am wondering how to add a device. I have a running homepilot instance and under objects I see the "dummy" devices. But how to i add one of my devices (e.g. an actuator?) 

Thanks you!

**Comment by homecineplexx** [comment]
hi
sorry, but i think you don't understand the working of the adapter in ioBroker.
you can't add a device with this adapter. you add the devices in the homepilot himself and this adapter makes a call and gets all the devices from the homepilot!

and i dont know what kind of "dummy"  device you mean, because there is no dummy device!
can you make a screenshot what you mean, please?
