### ISSUE TITLE
Sync issues with very "full" homepilot

### ISSUE THREAD

**Issue by hundertvolt1** [homecineplexx/ioBroker.homepilot20#60]
I am trying to connect the homepilot20 adapter to my HomePilot v3.

The HomePilot itself actually is very close to its limits: 84 physical DuoFern devices, Huebridge, allover above 200 logical devices, and several hundred scenes and triggers. Operation as such is perfectly stable, but the web interface often crashes ("Ups! Etwas ist schiefgelaufen!") by just opening a device / scene / trigger, while the configuration with the Android app is almost flawless. I already reported this to Rademacher and there was some slight improvement with the last update, but not really well yet.

Maybe this is somewhat linked to the issues I see in ioBroker. The adapter instance connects to the HomePilot, the attributes are generally available and updated, but the log is totally flooded with hundreds of warnings of such type:

```
  | Read  sensors -> Cannot connect to Homepilot:  {"statusCode":504,"body":"<!DOCTYPE  html>\n<html>\n<head>\n<title>Error</title>\n<style>\nhtml  { color-scheme: light dark; }\nbody { width: 35em; margin: 0  auto;\nfont-family: Tahoma, Verdana, Arial, sans-serif;  }\n</style>\n</head>\n<body>\n<h1>An error  occurred.</h1>\n<p>Sorry, the page you are looking for is  currently unavailable.<br/>\nPlease try again  later.</p>\n<p>If you are the system administrator of this  resource then you should check\nthe error log for  details.</p>\n<p><em>Faithfully yours,  nginx.</em></p>\n</body>\n</html>\n","headers":{"server":"nginx/1.22.1","date":"Tue,  12 Sep 2023 20:37:49  GMT","content-type":"text/html","content-length":"497","connection":"close","etag":"\"6452a22a-1f1\""},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"192.168.85.5","port":80,"hostname":"192.168.85.5","hash":null,"search":"?devtype=Sensor","query":"devtype=Sensor","pathname":"/v4/devices","path":"/v4/devices?devtype=Sensor","href":"http://192.168.85.5/v4/devices?devtype=Sensor"},"method":"GET","headers":{"0":{"Cookie":["HPSESSION=pr1BPmSgK95Yf7cIAG9L0Uidfg5kKw0xc96wcFlPH7M7Mlb7NoisbKzrRrJpr6eW;   Path=/"]},"1":{"Content-Type":"application/json"},"cookie":"HPSESSION=pr1BPmSgK95Yf7cIAG9L0Uidfg5kKw0xc96wcFlPH7M7Mlb7NoisbKzrRrJpr6eW"}}}
-- | --
```

It's all the same for actuators, scenes, sensors and transmitters. For me it does not look like a bug as such, but rather an issue likely to occur with a very "full" Homepilot - but maybe there is a way to get around this (e.g. allowing a larger response timeout or the like)... Maybe you have an idea; if you need more infos please let me know! :)

**Comment by homecineplexx** [comment]
Hello
yes, this is an issus of the homepilot himself, if he isn't available anymore.

but i am working on an fix for that, if the polling of e.g. scenes got an error because of 504 or something like that, i will do the next polling 24 hours later...i think sensor, transmitter, scenes are not so important as actuators

;-)

**Comment by MrTomRocker** [comment]
I had the same issue. I have 163 overall devices visible in the homepilot. 
![image](https://github.com/user-attachments/assets/274c9fa4-1b58-4697-a548-abca69841710)

I am using the Homepilot-2 with motor shutters, Schaltaktoren, dimmers, door contacts, a lot of "Mehrfachwandtaster", a HUE bridge, heating actors and an environment sensor. 
I have a multihost IO-Broker setup and the homepilot20 adapter is running in a docker hosted IObroker on a Synology DSM-720+, which generates high networkpressure to the homepilot.  

Due to the asynchronous character of the request( - command, I found out, that a lot of parallel requests are send to the Homepilot. In my case, with the current firmware this leads to following behaviour: 
- I cannot use the Web-UI and App of the Homepilot, if the adapter is active
- The Homepilot crashes at least twice a week, if the adapter is active

With the current firmware and my hardware setup, I cannot use this adapter. That is why I tried to do a fix for the issue with the parallel requests. I have implemented a sequential polling cycle with async and await. I also have optimized the reuquests itself. 
It is possible to refresh most of the devices by accessing http://IP/v4/devices and http://IP/devices. But for some of the transmitters, like the "Mehrfachwandtaster" you also need to read the device itself to get the TIMESTAMP informations, e.g. KEY_PUSH_CH3_EVT.

With my changes in the code, the Web-UI and App is now very responsive, even if this adapter is active. Also I can read out 8 Mehrfachwandtaster every second. This makes reaction to button presses also much more responsive than in the past. You can find my solution here: [https://github.com/MrTomRocker/ioBroker.homepilot20].

I will also open a pull request which should fix this problem.

**Comment by homecineplexx** [comment]
I added the pull request  and merged it to my code and build the new version 0.66
